# Basic settings
homeassistant:
  name: !secret address
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  unit_system: metric
  time_zone: Europe/Amsterdam
  
  packages: !include_dir_named packages
  
# Update
updater:
  reporting: false
  include_used_components: false

# Enable yaml mode for lovelace
lovelace:
  mode: yaml

influxdb:
  host: nmrsmn.duckdns.org
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  ssl: true
#  verify_ssl: true
  max_retries: 5
  default_measurement: state

# Other config
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
    
# Lyric
#lyric:
#  client_id: !secret lyric_client_id
#  client_secret: !secret lyric_client_secret

# Text to speech
tts:
  - platform: google_translate
  
mqtt:
  broker: !secret cloudmqtt_server
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_user
  password: !secret cloudmqtt_pass

# Includes
zone: !include zones.yaml