# Basic settings
homeassistant:
  name: !secret address
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  unit_system: metric
  time_zone: Europe/Amsterdam
  
  packages: !include_dir_named packages
  
# Update
updater:
  reporting: false
  include_used_components: false
  
# Enable iOS
ios:

# Enable yaml mode for lovelace
lovelace:
  mode: yaml

# Other config
default_config:

http:
    base_url: !secret hass_base_url
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
  
mqtt:
  broker: !secret cloudmqtt_server
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_user
  password: !secret cloudmqtt_pass
  
owntracks:
  max_gps_accuracy: 100
  waypoints: false
  mqtt_topic: "owntracks/#"
  events_only: false

# Includes
zone: !include zones.yaml