title: !secret address
resources:
  - url: /local/plugins/auto-entities.js
    type: module
  - url: /local/plugins/card-mod.js
    type: module
views:
  - id: Home
    view: true
    icon: mdi:home
    name: "Home"
    path: "home"
    badges:
      - person.niels_marsman
    cards:
      #- type: horizontal-stack
      #  cards:
      #    - type: picture-entity
      #      entity: person.niels
      #      image: /local/persons/rudolf.jpg
      #      #show_name: false
      #      aspect_ratio: 1x1
      #    - type: picture-entity
      #      entity: person.michelle
      #      image: /local/persons/leny.jpg
      #      show_name: false
      #      aspect_ratio: 1x1
    
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: picture-entity
              name: Vandaag
              entity: sensor.garbage_today
              state_image:
                'GFT': /local/afvalwijzer/gft.png
                'Papier': /local/afvalwijzer/papier.png
                'Restafval': /local/afvalwijzer/rest.png
                'Plastic': /local/afvalwijzer/plastic.png
              image: /local/afvalwijzer/kliko.png
  
            - type: picture-entity
              name: Morgen
              entity: sensor.garbage_tomorrow
              state_image:
                'GFT': /local/afvalwijzer/gft.png
                'Papier': /local/afvalwijzer/papier.png
                'Restafval': /local/afvalwijzer/rest.png
                'Plastic': /local/afvalwijzer/plastic.png
              image: /local/afvalwijzer/kliko.png
  
        - type: markdown
          content: |
           Vandaag is het <font color='green'>{{ states.sensor.today.state }}</font>.

        - card:
            type: glance
          filter:
            include:
            - entity_id: sensor.*_formatted
          sort:
            attribute: days
            method: attribute
            numeric: true
            count: 4
          type: 'custom:auto-entities'
          
        - type: thermostat
          entity: climate.tstat_3a657d
          
  - id: Usage
    panel: true
    icon: mdi:gauge
    name: "Verbruik"
    path: "usage"
    cards:
      - type: custom:mod-card
        style: |
         ha-card { padding:10px; }
        card:
          type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - type: entities
                  title: Meterstanden
                  show_header_toggle: false
                  entities:
                    - entity: sensor.dsmr_energy_delivered_t1
                    - entity: sensor.dsmr_energy_delivered_t2
                    - entity: sensor.dsmr_energy_returned_t1
                    - entity: sensor.dsmr_energy_returned_t2
            - type: vertical-stack
              cards:
                - type: sensor
                  entity: sensor.dsmr_power_delivered
                  graph: line
#                - type: sensor
#                  entity: sensor.dsmr_power_returned
#                  graph: line
