- platform: workday
  name: workday-sensor-niels
  country: Netherlands
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
- platform: workday
  name: workday-sensor-michelle
  country: Netherlands
  workdays: [wed, thu, fri, sat]
  excludes: [sun, holiday]