# Booleans for getting reminders
input_boolean:
  garbage_ready_for_pickup:
    name: Afval is aan de weg gezet
    initial: False
  garbage_reminder_niels:
    name: Niels herinneren het afval bij de weg te zetten
    initial: True
  garbage_reminder_michelle:
    name: Michelle herinneren het afval bij de weg te zetten
    initial: True
    
input_datetime:
  garbage_reminder_snoozed_niels:
    name: Afval herinnering gedempt (Niels)
    has_date: True
    has_time: True
  garbage_reminder_snoozed_michelle:
    name: Afval herinnering gedempt (Michelle)
    has_date: True
    has_time: True

# Sensors
sensor:
  - platform: garbage
    postal: !secret postal
    housenumber: !secret housenumber
    labels:
      separator: "en"
      nothing: "Geen"

  # Formatted garbage types
  - platform: template
    sensors:
      garbage_gft_formatted:
        friendly_name: "GFT"
        entity_picture_template: "/local/afvalwijzer/gft.png"
        value_template: "{{ states.sensor.garbage_gft.state }}"
        attribute_templates:
          days: "{{ state_attr('sensor.garbage_gft', 'days') }}"
        
      garbage_papier_formatted:
        friendly_name: "Papier"
        entity_picture_template: "/local/afvalwijzer/papier.png"
        value_template: "{{ states.sensor.garbage_papier.state }}"
        attribute_templates:
          days: "{{ state_attr('sensor.garbage_papier', 'days') }}"
      
      garbage_pmd_formatted:
        friendly_name: "PMD"
        entity_picture_template: "/local/afvalwijzer/plastic.png"
        value_template: "{{ states.sensor.garbage_pmd.state }}"
        attribute_templates:
          days: "{{ state_attr('sensor.garbage_pmd', 'days') }}"
        
      garbage_restafval_formatted:
        friendly_name: "Restafval"
        entity_picture_template: "/local/afvalwijzer/rest.png"
        value_template: "{{ states.sensor.garbage_restafval.state }}"
        attribute_templates:
          days: "{{ state_attr('sensor.garbage_restafval', 'days') }}"
            
      garbage_kerstbomen_formatted:
        friendly_name: "Kerstboom"
        entity_picture_template: "/local/afvalwijzer/kerstbomen.png"
        value_template: "{{ states.sensor.garbage_kerstbomen.state }}"
        attribute_templates:
          days: "{{ state_attr('sensor.garbage_kerstbomen', 'days') }}"

      garbage_tuinafval_formatted:
        friendly_name: "Tuinafval"
        entity_picture_template: "/local/afvalwijzer/tuinafval.png"
        value_template: "{{ states.sensor.garbage_tuinafval.state }}"
        attribute_templates:
          days: "{{ state_attr('sensor.garbage_tuinafval', 'days') }}"
              
      garbage_grofvuil_formatted:
        friendly_name: "Grofvuil"
        entity_picture_template: "/local/afvalwijzer/grofvuil.png"
        value_template: "{{ states.sensor.garbage_grofvuil.state }}"
        attribute_templates:
            days: "{{ state_attr('sensor.garbage_grofvuil', 'days') }}"
       
# Notification actions
ios:
  push:
    categories:
      - name: Garbage
        identifier: 'garbage'
        actions:
          - identifier: 'MARK_COMPLETED'
            title: 'Afval aan de weg gezet'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'DISMISS_NOTIFICATION'
            title: 'Melding dempen (6 uur)'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'STOP_NOTIFICATION'
            title: 'Melding niet meer tonen'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'

# Automations
automation:
  - alias: reset_garbage_ready_for_pickup
    trigger:
      platform: state
      entity_id: input_boolean.garbage_ready_for_pickup
      to: 'on'
      for:
        hours: 18
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.garbage_ready_for_pickup

  - alias: mark_garbage_ready_for_pickup
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_COMPLETED
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.garbage_ready_for_pickup

# Automations for Niels
  - alias: dismiss_garbage_notification_niels
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISMISS_NOTIFICATION
        sourceDeviceID: iphone_van_niels
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.garbage_reminder_snoozed_niels
        data_template:
          datetime: >-
            {% set ts_now = as_timestamp(now()) | int %}
            {% set ts_a = ts_now + (60 * 60 * 6) %}
            {{ ts_a | timestamp_custom("%Y-%m-%d %H:%M:%S") }}
            
  - alias: stop_garbage_notification_niels
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: STOP_NOTIFICATION
        sourceDeviceID: iphone_van_niels
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.garbage_reminder_niels

  - alias: notify_niels_of_garbage_pickup_tomorrow # Sends reminder every hour
    trigger:
      platform: time_pattern
      minutes: 00
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.garbage_ready_for_pickup
          state: 'off' 
        - condition: state
          entity_id: input_boolean.garbage_reminder_niels
          state: 'on' 
        - condition: template
          value_template: >
            {% set ts_now = as_timestamp(now()) %}
            {% set ts_snooze = state_attr('input_datetime.garbage_reminder_snoozed_niels', 'timestamp') %}
            {{ ts_now > ts_snooze }}
        - condition: time
          after: '18:00:00'
          before: '23:01:00'
        - condition: template
          value_template: "{{ states('sensor.garbage_tomorrow') != 'Geen' }}"
    action:
      - service: notify.niels
        data:
          title: "Afvalinzameling"
          message: "Morgen wordt het {{ states.sensor.garbage_tomorrow.state }} opgehaald!"
          data:
            apns_headers:
              'apns-collapse-id': 'garbage-collection-tomorrow'
            push:
              thread-id: 'Afvalinzameling'

  - alias: notify_niels_of_garbage_pickup_today # Sends reminder every 30 minutes
    trigger:
      platform: time_pattern
      minutes: '/30'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.garbage_ready_for_pickup
          state: 'off' 
        - condition: state
          entity_id: input_boolean.garbage_reminder_niels
          state: 'on'
        - condition: template
          value_template: >
            {% set ts_now = as_timestamp(now()) %}
            {% set ts_snooze = state_attr('input_datetime.garbage_reminder_snoozed_niels', 'timestamp') %}
            {{ ts_now > ts_snooze }}
        - condition: time
          after: '06:00:00'
          before: '10:30:00'
        - condition: template
          value_template: "{{ states('sensor.garbage_today') != 'Geen' }}"
    action:
      - service: notify.niels
        data:
          title: "Afvalinzameling"
          message: "Vandaag wordt het {{ states.sensor.garbage_today.state }} opgehaald!"
          data:
            apns_headers:
              'apns-collapse-id': 'garbage-collection-today'
            push:
              thread-id: 'Afvalinzameling'

# Automations for Michelle
  - alias: dismiss_garbage_notification_michelle
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISMISS_NOTIFICATION
        sourceDeviceID: iphone_van_michelle
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.garbage_reminder_snoozed_michelle
        data_template:
          datetime: >-
            {% set ts_now = as_timestamp(now()) | int %}
            {% set ts_a = ts_now + (60 * 60 * 6) %}
            {{ ts_a | timestamp_custom("%Y-%m-%d %H:%M:%S") }}
            
  - alias: stop_garbage_notification_michelle
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: STOP_NOTIFICATION
        sourceDeviceID: iphone_van_michelle
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.garbage_reminder_michelle

  - alias: notify_michelle_of_garbage_pickup_tomorrow # Sends reminder every hour
    trigger:
      platform: time_pattern
      minutes: 00
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.garbage_ready_for_pickup
          state: 'off' 
        - condition: state
          entity_id: input_boolean.garbage_reminder_michelle
          state: 'on' 
        - condition: template
          value_template: >
            {% set ts_now = as_timestamp(now()) %}
            {% set ts_snooze = state_attr('input_datetime.garbage_reminder_snoozed_michelle', 'timestamp') %}
            {{ ts_now > ts_snooze }}
        - condition: time
          after: '19:00:00'
          before: '23:01:00'
        - condition: template
          value_template: "{{ states('sensor.garbage_tomorrow') != 'Geen' }}"
    action:
      - service: notify.michelle
        data:
          title: "Afvalinzameling"
          message: "Morgen wordt het {{ states.sensor.garbage_tomorrow.state }} opgehaald!"
          data:
            apns_headers:
              'apns-collapse-id': 'garbage-collection-tomorrow'
            push:
              thread-id: 'Afvalinzameling'

  - alias: notify_michelle_of_garbage_pickup_today # Sends reminder every 30 minutes
    trigger:
      platform: time_pattern
      minutes: '/30'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.garbage_ready_for_pickup
          state: 'off' 
        - condition: state
          entity_id: input_boolean.garbage_reminder_michelle
          state: 'on'
        - condition: template
          value_template: >
            {% set ts_now = as_timestamp(now()) %}
            {% set ts_snooze = state_attr('input_datetime.garbage_reminder_snoozed_michelle', 'timestamp') %}
            {{ ts_now > ts_snooze }}
        - condition: time
          after: '06:00:00'
          before: '10:30:00'
        - condition: template
          value_template: "{{ states('sensor.garbage_today') != 'Geen' }}"
    action:
      - service: notify.michelle
        data:
          title: "Afvalinzameling"
          message: "Vandaag wordt het {{ states.sensor.garbage_today.state }} opgehaald!"
          data:
            apns_headers:
              'apns-collapse-id': 'garbage-collection-today'
            push:
              thread-id: 'Afvalinzameling'
