binary_sensor:
  - platform: workday
    name: workday-niels
    country: Netherlands
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

# Notifications
notify: 
  - name: niels
    platform: group
    services:
      - service: mobile_app_iphone_van_niels
  - name: household
    platform: group
    services:
      - service: niels
      - service: lg_49nano866na_woonkamer
  - name: none
    platform: group
    services:
    
