binary_sensor:
  - platform: workday
    name: workday-niels
    country: Netherlands
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
  - platform: workday
    name: workday-michelle
    country: Netherlands
    workdays: [wed, thu, fri, sat]
    excludes: [sun, holiday]

# Notifications
notify: 
  - name: niels
    platform: group
    services:
      - service: ios_iphone_van_niels
  - name: michelle
    platform: group
    services:
      - service: ios_iphone_van_michelle
  - name: household
    platform: group
    services:
      - service: niels
      - service: michelle
  - name: none
    platform: group
    services:
