
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'
      
  - platform: season
    type: astronomical
    
  - platform: moon
  
  - platform: uptime
  
  - platform: template
    sensors:
      today:
        friendly_name: "Vandaag"
        value_template: '{{ now().strftime("%-d %B %Y") }}'